# -*- coding: utf-8 -*-
"""olympic_data_mining_gianni v. 11 giugno 2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQl_SHzVMuXJOMG2H5Vqy0RyaAaBSsnj

# Progetto: "Non solo Giochi"
## Analisi dei fattori socio-economici e demografici nel successo olimpico

Questo notebook esplora i determinanti strutturali che influenzano la performance dei Paesi nelle Olimpiadi estive, integrando i dati storici dei medaglieri con gli indicatori macroeconomici della World Bank.

### 🎯 Domanda di Ricerca & Obiettivi
In che misura il numero di medaglie è determinato da fattori strutturali (ricchezza e demografia) rispetto a fattori qualitativi (efficienza del sistema sportivo, investimenti mirati, cultura locale)?

Per rispondere a questo quesito, il lavoro è strutturato nelle seguenti fasi:
1. **Analisi Esplorativa dei Dati (EDA):** Studio delle distribuzioni e delle correlazioni storiche.
2. **Segmentazione (Clustering K-Means):** Raggruppamento dei Paesi in base ai profili socio-economici.
3. **Modellazione Predittiva:** Sviluppo di modelli di regressione lineare (OLS) e algoritmi non lineari (Random Forest).
4. **Analisi dell'Efficienza:** Studio dei residui per identificare i Paesi virtuosi (over-performer) e quelli inefficienti (under-performer).

Import librerie

Per iniziare, dobbiamo importare tutte le librerie Python che useremo nel notebook:
* `pandas` per gestire i dati,
* `numpy` per calcoli numerici,
* `matplotlib` e `seaborn` per fare grafici,
* e poi vari strumenti da `sklearn` per il clustering, la standardizzazione e i modelli di machine learning.

E' stao anche aggiunto `warnings` per i da messaggi di avviso e ho impostato uno stile per i grafici e la loro dimensione predefinita.
"""

# Cella 1 : Import librerie

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

from sklearn.preprocessing import StandardScaler

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.preprocessing import MinMaxScaler
from math import pi

from sklearn.linear_model import LinearRegression

import plotly.express as px

warnings.filterwarnings('ignore')

sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (12,6)

"""Caricamento Dataset

Carichiamo il nostro dataset! Ho usato `pd.read_csv()` per leggere il file 'dataset_olimpiadi_indicatori_ita.csv' e salvarlo in un DataFrame di pandas chiamato `df`.

Poi, per dare un'occhiata veloce a come sono i dati, ho stampato le prime 3 righe con `df.head(3)` e ho usato `df.info()` per vedere un riassunto delle colonne, dei tipi di dato e se ci sono valori mancanti. Così capiamo subito con cosa abbiamo a che fare.
"""

# Cella 2 : Caricamento Dataset

df = pd.read_csv('dataset_olimpiadi_indicatori_ita.csv')

display(df.head(3))
df.info()

"""### Analisi
Il dataset contiene informazioni su medaglie olimpiche e variabili macroeconomiche.
Sono presenti valori mancanti che verranno gestiti nelle fasi successive.

## Costruzione delle variabili avanzate

In questa fase vengono create nuove variabili utili per l’analisi.

In particolare:
- vengono calcolati indicatori di efficienza, come le medaglie ottenute rispetto al PIL
- viene costruito lo Score Medaglie, che assegna pesi differenti alle medaglie (oro, argento, bronzo), fornendo una misura più rappresentativa del successo olimpico

Queste variabili consentono di migliorare la qualità delle analisi successive.
"""

# Cella 3 : Costruzione Variabili Avanzate

#df['Medaglie_per_miliardo'] = df['Totale_Medaglie'] / (df['Popolazione_Totale']/1e6)
df['Medaglie_per_miliardo'] = df['Totale_Medaglie'] / (df['PIL_Assoluto_USD']/1e9)
df['Medaglie_per_PIL'] = df['Totale_Medaglie'] / df['PIL_Assoluto_USD']

df['Score_Medaglie'] = (
    df['Medaglie_Oro']*3 +
    df['Medaglie_Argento']*2 +
    df['Medaglie_Bronzo']
)

"""## Preparazione del dataset

Il dataset è stato filtrato al fine di selezionare un intervallo temporale coerente con la disponibilità dei dati economici.

Successivamente, sono state considerate solo le osservazioni complete rispetto alle variabili principali (PIL, popolazione e performance olimpica), al fine di garantire la qualità delle analisi.

## Scelta del periodo di analisi

L’analisi è stata estesa a partire dal 1964 al fine di aumentare la numerosità del campione e migliorare la robustezza statistica dei modelli.

Tuttavia, i dati relativi ai decenni precedenti risultano meno completi e caratterizzati da maggiore variabilità rispetto al periodo successivo al 1980.

Per questo motivo, è stato effettuato un confronto tra i due intervalli temporali, evidenziando un trade-off tra quantità e qualità dei dati.
"""

# Cella 4 : Filtro pulizia NaN

# Filtriamo il dataset per considerare solo le Olimpiadi dall'era moderna in poi
# (es. dal 1964, o dall'anno in cui i dati economici diventano più densi)
anno_inizio_analisi= 1964
df_moderno = df[df['Anno'] >= anno_inizio_analisi].copy()

# Ora possiamo applicare il dropna() solo sulle colonne chiave in modo molto più mirato
features_analisi = ['PIL_Assoluto_USD', 'Popolazione_Totale', 'Score_Medaglie']
df_analisi = df_moderno.dropna(subset=features_analisi).copy()

"""## Confronto tra diverse soglie temporali

Prima di procedere con le analisi, viene effettuato un confronto tra due possibili intervalli temporali (1964–oggi e 1980–oggi).

L’obiettivo è valutare il trade-off tra numerosità del campione e qualità dei dati, confrontando sia il numero di osservazioni sia la stabilità della relazione tra PIL e performance olimpica.

Questo passaggio consente di giustificare la scelta del periodo utilizzato nelle analisi successive.
"""

# Cella 5 Confronto tra due soglie temporali

df_1980 = df[df['Anno'] >= 1980]
df_1964 = df[df['Anno'] >= 1964]

print("Numero osservazioni dal 1964:", len(df_1964))
print("Numero osservazioni dal 1980:", len(df_1980))

# Confronto correlazione PIL - medaglie
corr_1964 = df_1964['PIL_Assoluto_USD'].corr(df_1964['Score_Medaglie'])
corr_1980 = df_1980['PIL_Assoluto_USD'].corr(df_1980['Score_Medaglie'])

print("Correlazione 1964:", corr_1964)
print("Correlazione 1980:", corr_1980)

print("\nDifferenza osservazioni:", len(df_1964) - len(df_1980))

"""L’estensione dell’analisi al periodo 1964–oggi consente di aumentare la numerosità del campione, ma introduce una maggiore eterogeneità storica.

Di conseguenza, i risultati vengono interpretati tenendo conto del trade-off tra robustezza statistica e comparabilità temporale.

## Gestione avanzata dei valori mancanti

Per garantire la qualità delle analisi, è stata effettuata una gestione strutturata dei valori mancanti.

Le variabili socio-economiche sono state interpolate linearmente su base temporale, per ciascun Paese, al fine di preservare la continuità delle serie storiche.

Le variabili con una quota eccessiva di dati mancanti sono state rimosse, mentre le osservazioni residue incomplete sono state eliminate.

Questo processo consente di ottenere un dataset coerente e adatto alle successive analisi modellistiche.
"""

# Cella 6 Gestione Avanzata dei Valori Mancanti

# 1. Ordinamento logico per Nazione e Anno (necessario per un'interpolazione corretta)
df_analisi = df_analisi.sort_values(by=['Nazione', 'Anno'])

# Selezioniamo le colonne socio-economiche che vogliamo interpolare.
# Inseriamo variabili con andamento tendenzialmente lineare (demografia, macroeconomia)
colonne_da_interpolare = [
    # Feature già presenti nel modello
    'Iscrizioni_Scuola_Primaria_perc',
    'Popolazione_Urbana',
    'Aspettativa_di_Vita',

    # Feature macroeconomiche
    'Spesa_Militare_perc_PIL',
    'Investimenti_Diretti_Esteri_perc_PIL',
    'Valore_Aggiunto_Industria_perc_PIL',
    'Valore_Aggiunto_Servizi_perc_PIL',

    # Feature demografiche e di benessere
    'Tasso_Urbanizzazione_perc',
    'Tasso_Mortalita_Infantile',
    'Densita_Popolazione'
]

# 2. Interpolazione lineare raggruppata per nazione
for col in colonne_da_interpolare:
    if col in df_analisi.columns:
        # L’interpolazione è stata limitata per evitare distorsioni nelle estremità delle serie temporali, dove la mancanza di dati potrebbe generare stime non realistiche.
        df_analisi[col] = df_analisi.groupby('Nazione')[col].transform(lambda group: group.interpolate(method='linear', limit_direction='forward'))

# 3. Rimozione delle colonne con un eccesso di valori mancanti irrisolti
# Se una colonna ha ancora il 40% o più di NaN (es. dati mai raccolti per molte nazioni), la eliminiamo
soglia_minima_dati_validi = len(df_analisi) * 0.60
df_analisi = df_analisi.dropna(thresh=soglia_minima_dati_validi, axis=1)

# 4. Drop finale delle singole righe rimaste con NaN per garantire la compatibilità con i modelli
df_analisi = df_analisi.dropna()

# Verifica finale del risultato
print(df_analisi.info())
print("\nValori mancanti residui:\n", df_analisi.isnull().sum())

"""# Analisi delle Correlazioni

In questa fase viene calcolata la matrice di correlazione tra le variabili numeriche, al fine di analizzarne le relazioni.

L’attenzione è posta sulle variabili maggiormente correlate allo Score Medaglie, in modo da individuare i principali fattori associati alla performance olimpica.

La rappresentazione tramite heatmap consente di visualizzare in modo immediato intensità e direzione delle correlazioni.
"""

# Cella 7 : Analisi delle correlazioni

corr = df_analisi.corr(numeric_only=True)

top_corr = corr[['Score_Medaglie']].sort_values(by='Score_Medaglie', ascending=False).head(10)

plt.figure(figsize=(6,8))

sns.heatmap(top_corr, annot=True, cmap='coolwarm', linewidths=0.5)

plt.title("Top correlazioni con Score Medaglie")
plt.show()

"""## Analisi delle correlazioni

L’analisi delle correlazioni consente di individuare le relazioni lineari tra le variabili economiche e la performance olimpica.

Lo Score Medaglie è utilizzato come variabile target, in quanto fornisce una misura più completa del successo sportivo.

La visualizzazione tramite heatmap permette di evidenziare in modo immediato l’intensità e la direzione delle correlazioni.

## Segmentazione per Reddito

### 1. Segmentazione per Reddito Pro Capite

Creiamo una nuova colonna chiamata `Fascia_Reddito_Pro_Capite` nel DataFrame `df_analisi` e visualizziamo il primo grafico.
  - Utilizza la funzione `pd.qcut()` per dividere i paesi in quattro (`q=4`) fasce di reddito pro capite (PIL pro capite in USD), assicurando che ogni fascia contenga circa lo stesso numero di osservazioni (quantili).
  - Le fasce sono etichettate come 'Basso', 'Medio-Basso', 'Medio-Alto' e 'Alto'.

### 2. Segmentazione per Reddito Totale (PIL Assoluto)

 In modo simile alla segmentazione per reddito pro capite, questa riga crea una nuova colonna `Fascia_Reddito_Totale`.
  - Questa volta, la divisione in quattro fasce è basata sul PIL assoluto del paese (`PIL_Assoluto_USD`) e visualizzamo il secondo grafico.


In sintesi, questa cella genera due box plot per analizzare come il successo olimpico (misurato in medaglie totali) sia correlato sia con la ricchezza pro capite (benessere del cittadino) sia con la ricchezza totale (dimensione economica complessiva) di un paese, dividendo i paesi in quattro gruppi per ciascun indicatore di reddito.
"""

# Cella 8 : Segmentazione per Reddito Pro Capite e Reddito Totale

# Segmentazione per Reddito Pro Capite
df_analisi['Fascia_Reddito_Pro_Capite'] = pd.qcut(df_analisi['PIL_Pro_Capite_USD'], q=4,
                               labels=['Basso','Medio-Basso','Medio-Alto','Alto'])

sns.boxplot(data=df_analisi, x='Fascia_Reddito_Pro_Capite', y='Totale_Medaglie', hue='Fascia_Reddito_Pro_Capite', palette='viridis', legend=False)
plt.title('Distribuzione Medaglie per Fascia di Reddito Pro Capite', fontsize=14, fontweight='bold')
plt.xlabel('Fascia di Reddito Pro Capite', fontsize=12)
plt.ylabel('Totale Medaglie Olimpiche', fontsize=12)
plt.show()

# Segmentazione per Reddito Totale (PIL Assoluto)
df_analisi['Fascia_Reddito_Totale'] = pd.qcut(df_analisi['PIL_Assoluto_USD'], q=4,
                               labels=['Basso','Medio-Basso','Medio-Alto','Alto'])

plt.figure(figsize=(12,6))
sns.boxplot(data=df_analisi, x='Fascia_Reddito_Totale', y='Totale_Medaglie', hue='Fascia_Reddito_Totale', palette='magma', legend=False)
plt.title('Distribuzione Medaglie per Fascia di Reddito Totale', fontsize=14, fontweight='bold')
plt.xlabel('Fascia di Reddito Totale', fontsize=12)
plt.ylabel('Totale Medaglie Olimpiche', fontsize=12)
plt.show()

"""Questa cella genera due grafici a dispersione (scatterplot) per visualizzare la relazione tra due diverse metriche economiche (PIL Assoluto e PIL Pro Capite) e il successo olimpico (Totale Medaglie).

### 1. Primo Grafico: Relazione tra PIL Assoluto e Totale Medaglie
Questo grafico esplora come la ricchezza complessiva di un paese influenzi il numero di medaglie vinte.

### 2. Secondo Grafico: Relazione tra PIL Pro Capite e Totale Medaglie
Questo grafico analizza come la ricchezza media per abitante di un paese si relaziona con il numero di medaglie.


Ho messo l'asse X in scala logaritmica (`plt.xscale('log')`). Questo perché il PIL ha valori molto diversi (da piccoli a enormi) e la scala logaritmica aiuta a visualizzare meglio le relazioni, soprattutto se ci sono grandi differenze tra i dati. Così possiamo vedere se c'è una tendenza o dei raggruppamenti particolari.

In sintesi, questa cella ci permette di confrontare due diverse prospettive sulla relazione tra la ricchezza di un paese e il suo successo olimpico, utilizzando grafici a dispersione con scala logaritmica per un'analisi più efficace.
"""

# Cella 9 : Grafici PIL/Medaglie (Interattivi con Tooltip)

# Primo grafico: PIL Assoluto vs Totale Medaglie
fig1 = px.scatter(
    data_frame=df_analisi,
    x='PIL_Assoluto_USD',
    y='Totale_Medaglie',
    log_x=True,
    trendline="ols",
    hover_name='Nazione',
    hover_data={'PIL_Assoluto_USD': ':,d', 'Totale_Medaglie': True},
    title='Relazione tra PIL Assoluto e Totale Medaglie Olimpiche (Interattivo)',
    labels={
        'PIL_Assoluto_USD': 'PIL Assoluto (USD) - Scala Logaritmica',
        'Totale_Medaglie': 'Totale Medaglie Olimpiche'
    },
    template='plotly_white'
)
fig1.show()


# Analisi della regressione (statistiche)
import statsmodels.api as sm
results = px.get_trendline_results(fig1)

model = results.iloc[0]["px_fit_results"]
print(model.summary())


# Secondo grafico: PIL Pro Capite vs Totale Medaglie
fig2 = px.scatter(
    data_frame=df_analisi,
    x='PIL_Pro_Capite_USD',
    y='Totale_Medaglie',
    log_x=True,
    trendline="ols",
    hover_name='Nazione',
    hover_data={'PIL_Pro_Capite_USD': ':,d', 'Totale_Medaglie': True},
    title='Relazione tra PIL Pro Capite e Totale Medaglie Olimpiche (Interattivo)',
    labels={
        'PIL_Pro_Capite_USD': 'PIL Pro Capite (USD) - Scala Logaritmica',
        'Totale_Medaglie': 'Totale Medaglie Olimpiche'
    },
    template='plotly_white'
)
fig2.show()

# Analisi della regressione (statistiche)
import statsmodels.api as sm
results = px.get_trendline_results(fig2)

model = results.iloc[0]["px_fit_results"]
print(model.summary())

"""## Confronto tra PIL totale e PIL pro capite

L’analisi delle regressioni lineari evidenzia differenze significative nel potere esplicativo tra il PIL totale e il PIL pro capite rispetto al successo olimpico.

Il modello basato sul PIL assoluto presenta un coefficiente di determinazione pari a R² = 0.568, indicando che circa il 56.8% della variabilità nel numero di medaglie è spiegata dalla dimensione economica complessiva del Paese. Il modello risulta altamente significativo (p-value ≈ 0) e il coefficiente positivo conferma che all’aumentare del PIL aumenta la performance olimpica. Questo risultato suggerisce che la capacità economica aggregata rappresenta un fattore determinante, in quanto consente investimenti su larga scala in infrastrutture, formazione e tecnologie sportive.

Al contrario, il modello basato sul PIL pro capite presenta un potere esplicativo molto più limitato (R² = 0.082), indicando che il livello medio di benessere spiega solo una quota ridotta della variabilità osservata. Sebbene il modello risulti statisticamente significativo, la relazione appare decisamente più debole.

Il confronto tra i due modelli evidenzia quindi come la dimensione economica totale sia molto più rilevante rispetto al reddito medio individuale. In altre parole, il successo olimpico dipende principalmente dalla capacità complessiva di mobilitare risorse, piuttosto che dal livello medio di ricchezza della popolazione.

Nel complesso, i risultati suggeriscono che il successo olimpico è guidato prevalentemente da fattori strutturali legati alla scala economica del Paese, mentre variabili qualitative, come l’organizzazione del sistema sportivo e l’efficienza degli investimenti, contribuiscono a spiegare la variabilità residua.

## Efficienza olimpica

L’analisi dell’efficienza olimpica consente di valutare la capacità dei Paesi di trasformare le risorse disponibili in risultati sportivi.

In particolare, viene considerata la relazione tra popolazione e medaglie ottenute in rapporto al PIL, al fine di identificare Paesi con performance superiori o inferiori rispetto alle attese.

L’utilizzo della scala logaritmica sulla popolazione permette di rappresentare in modo più efficace la distribuzione dei dati.
"""

# Cella 10 : Efficienza Olimpica

fig = px.scatter(
    data_frame=df_analisi,
    x='Popolazione_Totale',
    y='Medaglie_per_miliardo',
    log_x=True,
    hover_name='Nazione',
    hover_data={'Popolazione_Totale': ':,d', 'Medaglie_per_miliardo': ':.2f'},
    title='Efficienza Olimpica: Popolazione vs Medaglie per Miliardo (Interattivo)',
    labels={
        'Popolazione_Totale': 'Popolazione Totale (Scala Logaritmica)',
        'Medaglie_per_miliardo': 'Medaglie per Miliardo di PIL' # Corrected label
    },
    template='plotly_white'
)

# Removed fig.update_yaxes(range=[0, 10.0]) as the scale for Medaglie_per_miliardo will be different
fig.show()

print ("Top nazioni per Efficenza Olimpica")
nazioni_efficienti = df_analisi.sort_values(by='Medaglie_per_miliardo', ascending=False)[['Nazione', 'Medaglie_per_miliardo']].drop_duplicates(subset=['Nazione']) # Changed from Medaglie_per_milione
display(nazioni_efficienti.head(10))

"""### Analisi dei risultati

L’analisi evidenzia una significativa eterogeneità nella relazione tra dimensione demografica ed efficienza olimpica.

In particolare, emergono Paesi con popolazione contenuta che ottengono livelli elevati di efficienza (elevato numero di medaglie rispetto alle risorse disponibili), indicando un utilizzo particolarmente efficace delle risorse.

Al contrario, alcuni Paesi con popolazione elevata mostrano livelli di efficienza inferiori, suggerendo che la disponibilità di capitale umano non si traduce automaticamente in successo sportivo.

La dispersione osservata nel grafico conferma che fattori aggiuntivi, quali organizzazione del sistema sportivo, investimenti mirati e qualità delle infrastrutture, giocano un ruolo fondamentale nella determinazione della performance olimpica.

Nel complesso, i risultati indicano che il successo olimpico non dipende esclusivamente dalla dimensione del Paese, ma anche dalla capacità di trasformare le risorse disponibili in risultati sportivi..

## Nazioni meno efficienti

L’analisi delle nazioni meno efficienti consente di individuare i Paesi che ottengono poche medaglie in relazione alle risorse disponibili.

Questi casi rappresentano situazioni in cui la dimensione economica o demografica non si traduce in un adeguato livello di performance sportiva, evidenziando possibili inefficienze nel sistema sportivo.

L’identificazione di questi Paesi permette di approfondire il ruolo di fattori non direttamente osservabili, quali organizzazione istituzionale, politiche sportive e allocazione delle risorse.
``
"""

# Cella 11 : Nazioni meno efficienti

# Filtriamo le nazioni con Medaglie_per_miliardo > 0
# Poi ordiniamo per inefficienza (lowest medals per miliardo) e prendiamo le prime 50 per una migliore visualizzazione nel plot
df_inefficienti_plot = df_analisi[df_analisi['Medaglie_per_miliardo'] > 0].sort_values(by='Medaglie_per_miliardo', ascending=True).head(50)

fig_inefficienti = px.scatter(
    data_frame=df_inefficienti_plot,
    x='Popolazione_Totale',
    y='Medaglie_per_miliardo',
    log_x=True,
    hover_name='Nazione',
    hover_data={'Popolazione_Totale': ':,d', 'Medaglie_per_miliardo': ':.2f'},
    title='Inefficienza Olimpica: Popolazione vs Medaglie per Miliardo (Interattivo - Top 50 Meno Efficienti)',
    labels={
        'Popolazione_Totale': 'Popolazione Totale (Scala Logaritmica)',
        'Medaglie_per_miliardo': 'Medaglie per Miliardo di PIL'
    },
    template='plotly_white',
    color_discrete_sequence=['red'] # Usa un colore diverso per distinguerlo
)

# Opzionalmente, puoi regolare il range dell'asse Y per ingrandire la parte bassa se necessario
# fig_inefficienti.update_yaxes(range=[0, 0.1]) # Esempio: imposta un range basso
fig_inefficienti.show()

print("Top 10 Nazioni meno efficienti (Medaglie per Miliardo)")
nazioni_inefficienti = df_analisi[df_analisi['Medaglie_per_miliardo'] > 0].sort_values(by='Medaglie_per_miliardo', ascending=True)[['Nazione', 'Medaglie_per_miliardo']].drop_duplicates(subset=['Nazione'])
display(nazioni_inefficienti.head(10).reset_index(drop=True))

"""### Analisi dei risultati

L’analisi evidenzia la presenza di Paesi che, nonostante la disponibilità di risorse economiche o demografiche rilevanti, ottengono un numero relativamente contenuto di medaglie.

Questi casi possono essere interpretati come esempi di inefficienza relativa, in cui la capacità di trasformare le risorse disponibili in risultati sportivi risulta limitata.

Le possibili spiegazioni includono una minore attenzione alle politiche sportive, una allocazione non ottimale delle risorse o una struttura organizzativa meno efficace.

Nel complesso, i risultati confermano che la disponibilità di risorse rappresenta una condizione necessaria ma non sufficiente per il successo olimpico, evidenziando il ruolo di fattori qualitativi nella determinazione della performance.

Questa cella è dedicata a capire come la correlazione tra PIL e medaglie è cambiata nel tempo. L'idea è vedere se le Olimpiadi sono diventate sempre più 'per ricchi'.

1.  **Calcolo della correlazione per ogni anno:** Ho creato un ciclo che va su ogni anno presente nel dataset. Per ogni anno, calcolo la correlazione di Pearson tra `PIL_Assoluto_USD` e `Score_Medaglie`. Se ci sono abbastanza dati per quell'anno (più di 10 paesi), salvo l'anno e la correlazione in una lista.
2.  **Grafico del trend:** Ho usato `seaborn.lineplot()` per disegnare l'andamento della correlazione nel tempo. Così vedo subito se sale, scende o resta stabile.
3.  **Linea di tendenza:** Ho aggiunto un `seaborn.regplot()` con una linea tratteggiata. Questo serve a mostrarci la tendenza generale, cioè se c'è un aumento o una diminuzione della correlazione nel lungo periodo.
4.  **Estetica:** Ho sistemato i titoli, le etichette degli assi e l'aspetto generale del grafico per renderlo più leggibile e professionale. Ho anche fissato l'asse Y per far vedere che la correlazione è sempre abbastanza alta.

## Evoluzione del legame tra PIL e successo olimpico

Per approfondire il ruolo della dimensione economica nel tempo, viene analizzata l’evoluzione della correlazione tra PIL e performance olimpica nelle diverse edizioni dei Giochi.

Questo approccio consente di verificare se l’importanza del PIL sia rimasta costante oppure abbia subito variazioni nel tempo.
"""

# Cella 12 : Analisi del Trend Storico (Correlazione PIL-Medaglie nel tempo)

# 1. Calcoliamo la correlazione per ogni singolo anno
trend_correlazione = []
anni = sorted(df_analisi['Anno'].unique())

for anno in anni:
    df_anno = df_analisi[df_analisi['Anno'] == anno]
    # Calcoliamo la correlazione solo se ci sono abbastanza dati per quell'anno
    if len(df_anno) > 10:
        corr = df_anno['PIL_Assoluto_USD'].corr(df_anno['Score_Medaglie'])
        trend_correlazione.append({'Anno': anno, 'Correlazione': corr})

df_trend = pd.DataFrame(trend_correlazione)

# 2. Creazione del grafico del trend
plt.figure(figsize=(10, 5))
sns.lineplot(
    data=df_trend,
    x='Anno',
    y='Correlazione',
    marker='o',
    markersize=8,
    linewidth=2.5,
    color='#e63946'
)

# 3. Aggiunta di una linea di tendenza lineare (Regplot) per evidenziare la direzione
sns.regplot(
    data=df_trend,
    x='Anno',
    y='Correlazione',
    scatter=False,
    color='#457b9d',
    line_kws={'linestyle':'--', 'linewidth': 2, 'alpha': 0.7}
)

# 4. Estetica e pulizia
plt.title("Correlazione tra PIL e Medaglie (1980-Oggi)", fontsize=14, fontweight='bold', pad=15)
plt.xlabel("Edizione Olimpica (Anno)", fontsize=12)
plt.ylabel("Indice di Correlazione (Pearson)", fontsize=12)

# Impostiamo l'asse Y per mostrare che la correlazione è comunque sempre forte (positiva)
plt.ylim(0.4, 1.0)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.xticks(anni, rotation=45)
sns.despine(left=True, bottom=True)

plt.tight_layout()
plt.show()

"""### Analisi evolutiva

Il grafico dell’andamento storico consente di analizzare in una prospettiva dinamica il rapporto tra sviluppo economico e successo olimpico.

Nel complesso, la correlazione tra PIL e performance olimpica si mantiene costantemente positiva e su livelli elevati, generalmente superiori a 0.60 e spesso prossimi a 0.80. Questo evidenzia come la relazione tra dimensione economica e risultati sportivi rappresenti un elemento strutturale e persistente nel tempo.

Si osservano tuttavia alcune discontinuità significative in corrispondenza delle edizioni del 1980 e del 1984. Tali anomalie sono riconducibili ai boicottaggi olimpici della Guerra Fredda, che hanno determinato l’assenza di interi blocchi geopolitici, alterando temporaneamente il legame tra PIL e distribuzione delle medaglie.

L’analisi della linea di tendenza suggerisce inoltre una lieve crescita della correlazione nel tempo, indicando un progressivo rafforzamento del legame tra risorse economiche e performance sportiva.

Questo risultato è coerente con un processo di crescente professionalizzazione dello sport olimpico, in cui il successo appare sempre più legato alla capacità di sostenere investimenti su larga scala in infrastrutture, tecnologia e formazione.

Nel complesso, l’evidenza empirica suggerisce una progressiva accentuazione del ruolo del capitale economico nel determinare il successo olimpico, a discapito di fattori puramente demografici o casuali.

## Preparazione dei dati per il clustering

Prima di applicare il clustering, le variabili vengono trasformate e standardizzate per garantire una rappresentazione coerente dei dati.

Le trasformazioni logaritmiche vengono utilizzate per ridurre la variabilità e gestire la presenza di valori estremi, mentre la standardizzazione consente di evitare che variabili con scale diverse influenzino in modo sproporzionato l’algoritmo.

Viene inoltre introdotta una variabile di interazione tra PIL e popolazione, al fine di catturare effetti congiunti tra dimensione economica e demografica.

## Clustering
"""

# Cella 13 : Preparazione per clustering

# Trasformazione logaritmica (log1p è ideale perché gestisce in automatico eventuali zeri)
df_analisi['PIL_Log'] = np.log1p(df_analisi['PIL_Assoluto_USD'])
df_analisi['Pop_Log'] = np.log1p(df_analisi['Popolazione_Totale'])

#Aggiunta per l'analisi dell'efficienza e del benessere
df_analisi['PIL_ProCapite_Log'] = np.log1p(df_analisi['PIL_Pro_Capite_USD'])

#Selezioniamo le nuove feature logaritmiche e il target pesato per il clustering. Rimuovo 'Score_Medaglie' perché includere il target (le medaglie) nel clustering crea una distorsione
features_log = ['PIL_Log', 'PIL_ProCapite_Log', 'Pop_Log', 'PIL_x_Pop']
# interazione tra PIL e popolazione
df_analisi['PIL_x_Pop'] = df_analisi['PIL_Log'] * df_analisi['Pop_Log']

# Ora applichiamo la standardizzazione su distribuzioni più "normali"
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_analisi[features_log])

"""### Analisi delle trasformazioni

Le trasformazioni applicate consentono di ottenere variabili più comparabili e adatte all’analisi multivariata.

La standardizzazione riduce il rischio di distorsioni nelle procedure di clustering, assicurando che tutte le variabili contribuiscano in modo equilibrato alla formazione dei gruppi.

## Regressione multipla

La regressione multipla consente di analizzare l’effetto simultaneo di più variabili sulla performance olimpica, controllando per la presenza delle altre.

Il modello include:
- PIL (in forma logaritmica)
- popolazione (in forma logaritmica)
- PIL pro capite

Questo approccio permette di valutare il contributo relativo di ciascuna variabile, isolandone l’effetto netto.
"""

# Cella 14 #Regressione multipla
from sklearn.linear_model import LinearRegression

features = ['PIL_Log', 'Pop_Log', 'PIL_ProCapite_Log']

X = df_analisi[features]
y = df_analisi['Score_Medaglie']

model_multi = LinearRegression()
model_multi.fit(X, y)

print("R² modello multiplo:", model_multi.score(X, y))
print("Coefficienti:", dict(zip(features, model_multi.coef_)))

coef_df = pd.DataFrame({
    'Variabile': features,
    'Coefficiente': model_multi.coef_
})

display(coef_df)

"""### Analisi dei risultati

Il modello di regressione multipla mostra un coefficiente di determinazione pari a R² ≈ 0.28, indicando che una quota limitata della variabilità della performance olimpica è spiegata congiuntamente dalle variabili considerate.

Tra le variabili incluse, il PIL presenta un coefficiente positivo e di entità elevata, confermando il suo ruolo centrale nel determinare il successo olimpico.

Al contrario, popolazione e PIL pro capite mostrano coefficienti negativi, suggerendo che, una volta controllato per la dimensione economica complessiva, il loro contributo marginale risulta meno rilevante o inversamente correlato.

Questo risultato indica la presenza di possibili effetti di collinearità tra le variabili economiche, in particolare tra PIL e PIL pro capite.

Nel complesso, il modello evidenzia come il fenomeno sia multidimensionale e non completamente spiegabile da un numero limitato di variabili, suggerendo il ruolo di fattori aggiuntivi quali efficienza del sistema sportivo, politiche pubbliche e qualità degli investimenti.

## Determinazione del numero ottimale di cluster

Per identificare il numero ottimale di cluster, viene utilizzato il metodo del gomito, che analizza la variabilità intra-cluster (WCSS) al variare del numero di gruppi..

##Metodo del Gomito
"""

# Cella 15 : Scelta del gomito

wcss = []
k_range = range(1, 10)

for k in k_range:
    # Aggiunto 'k-means++' per velocizzare e stabilizzare la convergenza iniziale
    km = KMeans(n_clusters=k, init='k-means++', random_state=42)
    km.fit(X_scaled)
    wcss.append(km.inertia_)

# Generazione del grafico formattato
plt.figure(figsize=(8, 5))
plt.plot(k_range, wcss, marker='o', linestyle='-', color='#1f77b4', linewidth=2, markersize=8)

# Personalizzazione per il report
plt.title('Metodo del Gomito: Identificazione dei Cluster Ottimali', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Numero di Cluster (k)', fontsize=12)
plt.ylabel('WCSS (Inerzia intra-cluster)', fontsize=12)
plt.xticks(k_range) # Forza la visualizzazione di tutti i numeri interi sull'asse X
plt.grid(True, linestyle=':', alpha=0.7)

"""### Analisi dei risultati

Il grafico del metodo del gomito evidenzia una marcata riduzione della variabilità intra-cluster nei primi valori di k, in particolare tra 1 e 3 cluster.

A partire da k ≈ 3–4, la curva mostra un progressivo appiattimento, indicando che l’aggiunta di ulteriori cluster comporta benefici marginali in termini di riduzione del WCSS.

Questo suggerisce che il numero ottimale di cluster sia compreso tra 3 e 4, rappresentando un buon compromesso tra semplicità del modello e capacità descrittiva.

## Validazione del clustering

Per confermare il numero ottimale di cluster, viene utilizzato il Silhouette Score, che misura la coesione interna e la separazione tra i gruppi.
"""

# Cella 16 : Validazione clustering con Silhouette Score

from sklearn.metrics import silhouette_score

print("Valutazione del numero ottimale di cluster (Silhouette Score):\n")

for k in range(2, 9):
    km = KMeans(n_clusters=k, random_state=42, init='k-means++')
    labels = km.fit_predict(X_scaled)
    score = silhouette_score(X_scaled, labels)

    print(f"k = {k} → Silhouette Score = {score:.3f}")

"""### Analisi dei risultati

Il Silhouette Score evidenzia un valore massimo per k = 2, indicando una netta separazione tra due gruppi principali.

Tuttavia, valori leggermente inferiori per k = 3 e k = 4 suggeriscono la presenza di una struttura più articolata, con sottogruppi economicamente differenziati.

Considerando congiuntamente il metodo del gomito e il Silhouette Score, la scelta di k = 3 o k = 4 rappresenta un buon compromesso tra qualità della segmentazione e interpretabilità dei risultati.

La presenza di valori relativamente vicini tra loro indica che la struttura dei dati non è rigidamente separata, ma presenta transizioni graduali tra gruppi.

Q## Clustering dei Paesi

Il modello K-Means viene applicato per segmentare i Paesi in gruppi omogenei sulla base delle caratteristiche economiche e demografiche.

Il numero di cluster è fissato a k = 3, in quanto rappresenta un buon compromesso tra qualità statistica e interpretabilità dei risultati.

Questa segmentazione consente di individuare diversi modelli di sviluppo socio-economico e di analizzarne la relazione con la performance olimpica.
"""

# Cella 17 : Addestramento e Visualizzazione ad alta dimensionalità

# 1. Addestramento (ipotizziamo k=3 dal gomito)
k_ottimale = 3
kmeans = KMeans(n_clusters=k_ottimale, init='k-means++', random_state=42)
df_analisi['Cluster_SocioEconomico'] = kmeans.fit_predict(X_scaled)

# Cella 13: Grafico Comparativo - PIL Assoluto vs PIL Pro Capite

# Configurazione dello spazio per due grafici verticali
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 14))

# 1. Primo Grafico: PIL Assoluto vs Score Medaglie
sns.scatterplot(
    data=df_analisi,
    x='PIL_Log',
    y='Score_Medaglie',
    hue='Cluster_SocioEconomico',
    size='Pop_Log',
    sizes=(30, 400),
    palette='viridis',
    alpha=0.7,
    edgecolor='w',
    ax=ax1
)
ax1.set_title('1. Potenza Economica (PIL Assoluto) vs Successo Olimpico', fontsize=13, fontweight='bold', pad=10)
ax1.set_xlabel('PIL Assoluto (Scala Logaritmica)', fontsize=11)
ax1.set_ylabel('Score Medaglie Olimpiche', fontsize=11)
ax1.grid(True, linestyle=':', alpha=0.6)
ax1.legend(bbox_to_anchor=(1.02, 1), loc='upper left', title='Cluster & Popolazione')

# 2. Secondo Grafico: PIL Pro Capite vs Score Medaglie
sns.scatterplot(
    data=df_analisi,
    x='PIL_ProCapite_Log',
    y='Score_Medaglie',
    hue='Cluster_SocioEconomico',
    size='Pop_Log',
    sizes=(30, 400),
    palette='viridis',
    alpha=0.7,
    edgecolor='w',
    ax=ax2
)
ax2.set_title('2. Benessere Economico (PIL Pro Capite) vs Successo Olimpico', fontsize=13, fontweight='bold', pad=10)
ax2.set_xlabel('PIL Pro Capite (Scala Logaritmica)', fontsize=11)
ax2.set_ylabel('Score Medaglie Olimpiche', fontsize=11)
ax2.grid(True, linestyle=':', alpha=0.6)
ax2.legend(bbox_to_anchor=(1.02, 1), loc='upper left', title='Cluster & Popolazione')

# Ottimizzazione degli spazi per evitare sovrapposizioni
plt.tight_layout()
plt.show()

# . Profilazione Statistica Finale
print("\nProfilo dei cluster identificati (Valori reali e Conteggio):\n")
profilo = df_analisi.groupby('Cluster_SocioEconomico')[['PIL_Assoluto_USD', 'PIL_Pro_Capite_USD', 'Popolazione_Totale', 'Score_Medaglie']].mean()
cluster_counts = df_analisi['Cluster_SocioEconomico'].value_counts().rename('Count').to_frame()
combined_profile = profilo.join(cluster_counts)

# Apply styling to the combined profile DataFrame for better visualization
styled_table = combined_profile.style.format({
    'PIL_Assoluto_USD': "€{:,.0f}",  # Format as currency with thousands separator
    'PIL_Pro_Capite_USD': "€{:,.2f}", # Format as currency with two decimal places
    'Popolazione_Totale': "{:,.0f}", # Format as integer with thousands separator
    'Score_Medaglie': "{:,.2f}",     # Format with two decimal places
    'Count': "{:,.0f}"              # Format as integer
}).set_caption("Profilo Dettagliato dei Cluster Socio-Economici") \
  .set_table_styles([
      {'selector': 'caption', 'props': [('font-size', '16px'), ('font-weight', 'bold')]},
      {'selector': 'th', 'props': [('background-color', '#f2f2f2'), ('color', 'black'), ('font-weight', 'bold')]},
      {'selector': 'td', 'props': [('text-align', 'center')]}
  ]) \
  .background_gradient(cmap='Blues', subset=['Score_Medaglie'])

display(styled_table)

"""### Analisi dei risultati

L’analisi dei cluster evidenzia una chiara segmentazione dei Paesi in tre gruppi distinti, caratterizzati da livelli differenti di sviluppo economico e performance olimpica.

Il primo cluster (Cluster 0) include Paesi con elevato PIL, popolazione significativa e alta performance olimpica. Questi rappresentano le principali potenze economiche e sportive, caratterizzate da una forte capacità di investimento e da sistemi sportivi consolidati.

Il secondo cluster (Cluster 1) raggruppa Paesi con livelli intermedi di sviluppo economico e performance limitata. Si tratta prevalentemente di economie di dimensioni ridotte o medio-piccole, con capacità di investimento più contenute e risultati sportivi modesti.

Il terzo cluster (Cluster 2) comprende Paesi con basso PIL pro capite e performance olimpica molto ridotta, che rappresentano economie emergenti o in via di sviluppo.

La visualizzazione grafica conferma queste differenze, mostrando una chiara separazione tra i gruppi lungo le dimensioni economiche e sportive. In particolare, il PIL totale emerge come variabile discriminante principale, mentre il PIL pro capite contribuisce a distinguere ulteriormente i livelli di benessere all’interno dei cluster.

Nel complesso, i risultati evidenziano come il successo olimpico sia fortemente associato alla struttura economica dei Paesi, confermando l’esistenza di un legame sistematico tra sviluppo economico e performance sportiva.

## Visualizzazione interattiva dei cluster

Per approfondire l’analisi dei cluster individuati, viene utilizzata una visualizzazione interattiva che consente di esplorare simultaneamente più dimensioni dei dati.

Il grafico rappresenta la relazione tra PIL e performance olimpica, integrando informazioni su popolazione, cluster di appartenenza e caratteristiche socio-economiche.

Questo strumento permette un’analisi più dettagliata dei singoli Paesi e facilita l’identificazione di pattern e anomalie.
"""

# Cella 18 : Scatterplot Interattivo Multidimensionale

fig = px.scatter(
    df_analisi,
    x="PIL_Assoluto_USD",
    y="Score_Medaglie",
    color=df_analisi['Cluster_SocioEconomico'].astype(str),
    size="Popolazione_Totale",
    hover_name="Nazione",
    hover_data=["PIL_Pro_Capite_USD", "Aspettativa_di_Vita", "Anno"],
    log_x=True,
    title="Esplorazione Interattiva dei Cluster Olimpici (Passa il mouse sui punti)",
    labels={"Cluster_SocioEconomico": "Cluster", "PIL_Assoluto_USD": "PIL Assoluto (USD)", "Score_Medaglie": "Score Medaglie"},
    template="plotly_white",
    color_discrete_sequence=['#e63946', '#457b9d', '#2a9d8f'] # Colori coerenti con il Radar Chart
)

fig.show()

"""### Analisi dei risultati

La visualizzazione interattiva consente di analizzare in modo integrato le principali dimensioni economiche, demografiche e sportive.

I risultati confermano la presenza di una chiara relazione tra PIL e successo olimpico, con i Paesi appartenenti al cluster delle economie avanzate posizionati nella parte alta della distribuzione, sia in termini di risorse economiche che di performance sportiva.

L’analisi evidenzia inoltre come la popolazione, rappresentata dalla dimensione dei punti, non sia di per sé sufficiente a garantire risultati elevati, in assenza di adeguate risorse economiche.

Attraverso l’esplorazione puntuale dei dati, è possibile identificare casi specifici di Paesi che si discostano dal comportamento medio, evidenziando situazioni di over e under performance rispetto alle attese.

La visualizzazione interattiva rappresenta quindi uno strumento complementare all’analisi statistica, permettendo di approfondire la composizione dei cluster e di individuare pattern non immediatamente osservabili nei grafici statici.

Nel complesso, i risultati rafforzano l’evidenza di una relazione strutturale tra sviluppo economico e successo olimpico, evidenziando al contempo l’importanza di fattori qualitativi nella spiegazione delle differenze tra Paesi.

## Valutazione della qualità del clustering

Per valutare la qualità della segmentazione ottenuta, viene utilizzato il Silhouette Score, che misura la coesione interna dei cluster e la separazione tra gruppi distinti.

Questo indicatore assume valori compresi tra -1 e 1, dove valori più elevati indicano una migliore definizione dei cluster.
"""

# Cella 19

score = silhouette_score(X_scaled, df_analisi['Cluster_SocioEconomico'])

print(f"Silhouette Score: {score:.3f}\n"
      "(misura la qualità del clustering: valori vicini a 1 indicano cluster ben separati, "
      "vicini a 0 cluster sovrapposti)")

"""### Analisi dei risultati

Il valore del Silhouette Score pari a circa 0.355 indica una qualità moderata del clustering.

Questo risultato suggerisce che i cluster individuati presentano una separazione discreta, ma non completamente netta, con una certa sovrapposizione tra i gruppi.

Tale evidenza è coerente con la natura dei dati socio-economici analizzati, in cui le differenze tra Paesi non sono rigidamente definite, ma caratterizzate da transizioni graduali.

Nonostante ciò, il clustering risulta comunque utile ai fini interpretativi, permettendo di individuare gruppi con caratteristiche economiche e sportive differenti.

Nel complesso, il risultato conferma la validità della segmentazione, pur evidenziandone i limiti in termini di separazione tra cluster.

## Profilazione multivariata dei cluster

Per analizzare in modo integrato le caratteristiche dei cluster individuati, viene utilizzato un Radar Chart, che consente di confrontare simultaneamente più dimensioni.

Le variabili selezionate rappresentano la dimensione economica, demografica, il livello di benessere e la performance sportiva.

I valori sono normalizzati per permettere un confronto diretto tra variabili con scale differenti, facilitando l’identificazione delle specificità di ciascun cluster.
"""

# Cella 20 : Profilazione Multivariata dei Cluster tramite Radar Chart

# 1. Selezioniamo le metriche chiave per definire il profilo dei cluster
features_radar = ['PIL_Log', 'Pop_Log', 'Aspettativa_di_Vita', 'Score_Medaglie']

# Nomi più eleganti per le etichette del grafico
etichette_radar = ['Ricchezza Statale\n(PIL)', 'Bacino Demografico\n(Popolazione)',
                   'Benessere Diffuso\n(Aspettativa di Vita)', 'Successo Sportivo\n(Score Medaglie)']

# 2. Calcoliamo la media di queste variabili per ogni singolo cluster
cluster_means = df_analisi.groupby('Cluster_SocioEconomico')[features_radar].mean()

# 3. Normalizziamo le medie tra 0 e 1 per farle convivere sullo stesso grafico
scaler_radar = MinMaxScaler()
cluster_means_scaled = pd.DataFrame(
    scaler_radar.fit_transform(cluster_means),
    columns=cluster_means.columns,
    index=cluster_means.index
)

# 4. Setup della geometria del Radar Chart (coordinate polari)
N = len(etichette_radar)
angoli = [n / float(N) * 2 * pi for n in range(N)]
angoli += angoli[:1] # Chiude il cerchio per il poligono

fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))

# Definiamo una palette di colori accesa per distinguere i cluster
colori = ['#e63946', '#457b9d', '#2a9d8f']
nomi_cluster = ['Cluster 0', 'Cluster 1', 'Cluster 2']

# 5. Costruzione dinamica dei poligoni per ciascun cluster
for i, row in cluster_means_scaled.iterrows():
    valori = row.values.flatten().tolist()
    valori += valori[:1] # Chiude il cerchio dei valori

    ax.plot(angoli, valori, linewidth=2.5, linestyle='solid', label=f'{nomi_cluster[i]}', color=colori[i])
    ax.fill(angoli, valori, alpha=0.15, color=colori[i])

# 6. Pulizia ed estetica del grafico
plt.xticks(angoli[:-1], etichette_radar, size=11, fontweight='bold')
ax.set_yticklabels([]) # Nascondiamo i numeri concentrici per un look più pulito
ax.spines['polar'].set_visible(False) # Rimuove il bordo esterno
plt.grid(color='#E8E8E8', linestyle='--', linewidth=1)

plt.title('Identikit dei Cluster: Confronto Multidimensionale', size=15, y=1.1, fontweight='bold')
plt.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1), fontsize=11, frameon=False)

plt.tight_layout()
plt.show()

"""### Analisi dei risultati

Il Radar Chart evidenzia una chiara differenziazione tra i cluster individuati, permettendo di osservare in modo sintetico le principali caratteristiche socio-economiche e sportive.

Il primo cluster è caratterizzato da valori elevati su tutte le dimensioni considerate, in particolare per quanto riguarda PIL, popolazione e performance olimpica. Questo gruppo rappresenta le principali potenze economiche e sportive, in grado di sostenere elevati livelli di investimento.

Il secondo cluster mostra valori intermedi, con livelli relativamente elevati di benessere ma dimensione economica e demografica più contenute. Questi Paesi presentano una buona capacità di conversione delle risorse in risultati sportivi, ma restano distanti dalle performance delle economie più avanzate.

Il terzo cluster è caratterizzato da valori più bassi su tutte le dimensioni, in particolare per quanto riguarda PIL e performance sportiva. Questo gruppo rappresenta economie emergenti, in cui la limitata disponibilità di risorse si riflette in risultati olimpici contenuti.

Nel complesso, il grafico evidenzia come il successo olimpico sia strettamente connesso alla struttura economica e al livello di sviluppo dei Paesi, confermando i risultati emersi nelle analisi precedenti.

La rappresentazione multivariata consente inoltre di evidenziare il carattere sistemico del fenomeno, in cui fattori economici, demografici e sociali concorrono congiuntamente alla determinazione della performance sportiva.

## Modello predittivo: Random Forest

Per stimare la performance olimpica in funzione delle variabili economiche e socio-demografiche, viene utilizzato un modello Random Forest.

Questo approccio consente di catturare relazioni non lineari tra le variabili e di migliorare la capacità predittiva rispetto ai modelli lineari.

Il modello include variabili economiche, demografiche e strutturali, tra cui il PIL, la popolazione, il livello di benessere e l’eventuale vantaggio del Paese ospitante.
``
"""

# Cella 21 : Random Forest

# =========================
# 1. Costruzione nuove variabili
# =========================

# Variabile host (vantaggio casa)
df_analisi['Host'] = (df_analisi['Nazione'] == df_analisi['Paese_Ospitante']).astype(int)


# =========================
# 2. Selezione feature
# =========================

features_modello = [
    'PIL_Log',
    'PIL_ProCapite_Log',
    'Pop_Log',
    'PIL_x_Pop',
    'Aspettativa_di_Vita',
    'Iscrizioni_Scuola_Primaria_perc',
    'Popolazione_Urbana',
    'Anno',
    'Host'
]

# Rimuoviamo eventuali NaN
df_model = df_analisi.dropna(subset=features_modello + ['Score_Medaglie']).copy()

X = df_model[features_modello]
y = np.log1p(df_model['Score_Medaglie'])


# =========================
# 3. Train/Test split
# =========================

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# =========================
# 4. Random Forest
# =========================

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

rf.fit(X_train, y_train)

# Predizioni in scala Log (per calcoli interni)
y_pred_log = rf.predict(X_test)

# Predizioni e Verità riportati alla scala Reale (per metriche e residui)
y_pred_real = np.expm1(y_pred_log)
y_test_real = np.expm1(y_test)

# =========================
# 5. Metriche (Solo su scala Reale)
# =========================

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

print("--- Modello Random Forest (Scala Reale) ---")
print(f"R-squared (R2): {r2_score(y_test_real, y_pred_real):.3f}")
print(f"MAE: {mean_absolute_error(y_test_real, y_pred_real):.2f} medaglie")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test_real, y_pred_real)):.2f} medaglie")

print("\nControllo overfitting:")
print(f"Train R²: {rf.score(X_train, y_train):.3f}")
print(f"Test R²: {rf.score(X_test, y_test):.3f}")

"""### Analisi dei risultati

Il modello Random Forest mostra una capacità predittiva discreta, con un coefficiente di determinazione pari a R² ≈ 0.44 sulla scala reale.

Gli errori di previsione risultano contenuti, con un errore medio assoluto di circa 7 medaglie, indicando una buona capacità del modello di approssimare i risultati osservati.

Il confronto tra le performance su training set (R² ≈ 0.91) e test set (R² ≈ 0.68) evidenzia la presenza di un moderato overfitting, tipico dei modelli basati su alberi. Tuttavia, la differenza tra i due valori rimane contenuta, suggerendo una buona capacità di generalizzazione.

Nel complesso, il modello non lineare migliora la capacità esplicativa rispetto alla regressione multipla, evidenziando l’importanza di relazioni complesse tra le variabili economiche e la performance olimpica.

Questi risultati confermano che il successo olimpico non è determinato da una singola variabile, ma dalla combinazione di fattori economici, demografici e strutturali.

## Analisi dei residui

Per valutare ulteriormente la qualità del modello predittivo, viene analizzata la distribuzione dei residui, ovvero la differenza tra valori osservati e valori predetti.

Questa analisi consente di verificare la presenza di errori sistematici e di valutare la capacità del modello di rappresentare correttamente i dati.
"""

#Cella 22
residuals = y_test_real - y_pred_real

plt.hist(residuals, bins=30)
plt.title("Distribuzione dei residui")
plt.xlabel("Errore")
plt.ylabel("Frequenza")
plt.show()

"""### Analisi dei risultati

La distribuzione dei residui risulta centrata intorno allo zero, indicando che il modello non presenta bias sistematici rilevanti nelle previsioni.

Tuttavia, la distribuzione appare asimmetrica e caratterizzata da code a destra, evidenziando la presenza di errori elevati in alcuni casi specifici.

Questi outlier rappresentano osservazioni in cui il modello sottostima significativamente la performance olimpica, suggerendo la presenza di fattori non completamente catturati dalle variabili incluse.

La concentrazione della maggior parte dei residui in prossimità dello zero indica comunque una buona capacità predittiva per la maggior parte delle osservazioni.

Nel complesso, l’analisi conferma che il modello è efficace nel catturare le tendenze generali, ma presenta limiti nel descrivere casi estremi o particolarmente efficienti.

## Identificazione di over e under performer

Per approfondire l’analisi dei residui, vengono individuati i Paesi che presentano le maggiori deviazioni rispetto alle previsioni del modello.

Questa procedura consente di identificare osservazioni con performance significativamente superiori o inferiori rispetto a quanto atteso sulla base delle variabili economiche e strutturali.
"""

# Cella 23 #Over / Under performer
df_test = X_test.copy()
df_test['Reali'] = y_test_real
df_test['Predetti'] = y_pred_real
df_test['Residuo'] = df_test['Reali'] - df_test['Predetti']

top_over = df_test.sort_values(by='Residuo', ascending=False).head(10)
top_under = df_test.sort_values(by='Residuo').head(10)

print("Top Over-performer:")
display(top_over)

print("\nTop Under-performer:")
display(top_under)

"""### Analisi dei risultati

L’analisi degli over e under performer evidenzia la presenza di deviazioni significative rispetto alle previsioni del modello.

Gli over performer mostrano residui molto elevati, indicando casi in cui la performance olimpica supera ampiamente quanto previsto dalle variabili economiche. In particolare, alcuni Paesi presentano scostamenti anche superiori a 150 medaglie, suggerendo l’esistenza di effetti eccezionali non catturati dal modello.

Al contrario, gli under performer evidenziano casi in cui il numero di medaglie risulta inferiore rispetto alle attese. Tuttavia, queste deviazioni risultano generalmente meno estreme rispetto agli over performer, indicando una maggiore variabilità nella capacità di eccellere rispetto a quella di sottoperformare.

Questi risultati suggeriscono che il modello tende a sottostimare le performance delle principali potenze sportive, evidenziando il ruolo di fattori aggiuntivi quali tradizione olimpica, investimenti strategici e organizzazione del sistema sportivo.

Nel complesso, l’analisi conferma che, pur essendo il PIL un fattore determinante, esistono Paesi in grado di ottenere risultati significativamente superiori grazie a elementi qualitativi non direttamente osservabili.
``

## Identificazione degli outlier

Per completare l’analisi dei residui, vengono identificati gli outlier, ovvero le osservazioni che presentano deviazioni particolarmente elevate rispetto alle previsioni del modello.

Gli outlier sono definiti come valori con residui superiori a una soglia pari a due deviazioni standard.
"""

# Cella 24 #Outlier
threshold = residuals.std() * 2

outliers = df_test[abs(df_test['Residuo']) > threshold]

print("Outliers individuati:")
display(outliers)

"""### Analisi dei risultati

L’analisi degli outlier evidenzia la presenza di osservazioni con deviazioni estremamente elevate rispetto alle previsioni del modello.

In particolare, emergono alcuni casi in cui il modello sottostima in modo significativo la performance olimpica, con residui molto elevati. Questi risultati suggeriscono la presenza di fattori specifici non catturati dalle variabili considerate, come investimenti eccezionali, politiche sportive particolarmente efficaci o condizioni favorevoli legate a eventi specifici.

La prevalenza di outlier positivi indica che il modello tende a sottostimare le prestazioni dei Paesi più performanti, in linea con quanto osservato nell’analisi degli over performer.

Questi casi rappresentano osservazioni rilevanti ai fini interpretativi, in quanto segnalano situazioni in cui la performance sportiva supera quanto atteso sulla base delle condizioni economiche.

Nel complesso, l’identificazione degli outlier consente di evidenziare i limiti del modello e di rafforzare l’ipotesi che fattori qualitativi e strategici giochino un ruolo fondamentale nel determinare il successo olimpico.

## Validazione del modello tramite cross-validation

Per valutare la robustezza del modello, viene applicata una cross-validation a k-fold, che consente di testare la performance su diversi sottoinsiemi del dataset.

Questo approccio permette di ottenere una stima più affidabile della capacità di generalizzazione del modello.
"""

# Cella 25 : Cross Validation

from sklearn.model_selection import cross_val_score

scores = cross_val_score(rf, X, y, cv=5, scoring='r2')

print("Cross-validation R²:")
print(scores)
print(f"Media R²: {scores.mean():.3f}")

"""### Analisi dei risultati

La cross-validation evidenzia un valore medio di R² pari a circa 0.26, inferiore rispetto a quello osservato sul test set.

Inoltre, si osserva una significativa variabilità tra i diversi fold, con la presenza di un valore negativo, indicativo di scarsa capacità predittiva in uno specifico sotto-campione.

Questi risultati suggeriscono che il modello presenta una certa instabilità e che le sue performance dipendono sensibilmente dalla composizione del dataset utilizzato per l’addestramento.

Questo comportamento è coerente con la natura dei dati, caratterizzati da una forte eterogeneità tra i Paesi e da una distribuzione fortemente asimmetrica delle medaglie, con pochi Stati dominanti e molti con performance limitate.

Nel complesso, il modello mostra una buona capacità predittiva su larga scala, ma una minore robustezza quando viene applicato a sottoinsiemi specifici dei dati.

Questo evidenzia come il fenomeno olimpico, pur influenzato da fattori strutturali, presenti una componente complessa e non pienamente stabile, legata a variabili non osservate e a dinamiche specifiche dei singoli Paesi.

## Importanza delle variabili

Per interpretare il modello Random Forest, viene analizzata l’importanza relativa delle variabili, che misura il contributo di ciascun fattore nella previsione della performance olimpica.

Questa analisi consente di individuare i principali driver del successo sportivo e di comprendere quali variabili influenzano maggiormente il modello.
"""

# Cella 26 per Insight
# Importanza variabili

importances = pd.Series(rf.feature_importances_, index=features_modello)

importances = importances.sort_values(ascending=True)

importances.plot(kind='barh')
plt.title("Importanza delle variabili - Random Forest")
plt.show()

print(importances)

"""### Analisi dei risultati

L’analisi delle feature importance evidenzia in modo chiaro il ruolo predominante del PIL nella determinazione della performance olimpica.

In particolare, il PIL (in forma logaritmica) presenta un’importanza nettamente superiore rispetto alle altre variabili, contribuendo per oltre il 50% alla capacità predittiva del modello. Questo risultato conferma quanto emerso nelle analisi precedenti, evidenziando il ruolo centrale della dimensione economica complessiva.

Le altre variabili, tra cui popolazione, urbanizzazione e indicatori di sviluppo, presentano un contributo più contenuto ma comunque rilevante, suggerendo che il fenomeno sia influenzato da una combinazione di fattori.

Il PIL pro capite mostra invece un’importanza relativamente bassa, indicando che il livello medio di benessere individuale ha un impatto meno diretto rispetto alla dimensione economica aggregata.

La variabile "Host" presenta un contributo trascurabile, suggerendo che il vantaggio del Paese ospitante ha un effetto limitato nel modello complessivo.

Nel complesso, i risultati confermano che il successo olimpico è principalmente guidato da fattori strutturali legati alla scala economica, mentre le altre variabili contribuiscono in modo complementare.

## Interpretabilità del modello (SHAP)

Per comprendere il contributo delle singole variabili alle previsioni del modello, viene utilizzata l’analisi SHAP (SHapley Additive exPlanations).

Questo approccio consente di interpretare in modo dettagliato il comportamento del modello, evidenziando sia l’importanza delle variabili sia la direzione del loro impatto sulla performance olimpica.
"""

# Cella 27
import shap

# Inizializza l'explainer sul modello Random Forest
explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(X_test)

# Summary plot: mostra l'impatto direzionale (es. PIL alto -> Medaglie alte)
shap.summary_plot(shap_values, X_test)

"""### Analisi dei risultati

Il summary plot SHAP consente di analizzare in modo approfondito l’impatto delle variabili sulle previsioni del modello, evidenziandone sia la rilevanza sia la direzione dell’effetto.

I risultati confermano il ruolo centrale del PIL e della popolazione, che mostrano una forte relazione positiva con la performance olimpica. In particolare, valori elevati di PIL sono associati a contributi positivi significativi nella previsione del numero di medaglie, mentre valori bassi comportano un impatto negativo.

Questo comportamento evidenzia una relazione non lineare, in cui l’aumento della dimensione economica si traduce in un incremento più che proporzionale della performance sportiva nelle fasce più alte.

Le variabili legate al benessere, come aspettativa di vita e PIL pro capite, mostrano un impatto positivo ma più contenuto, suggerendo che il livello medio di sviluppo contribuisce a migliorare la performance, pur non essendo determinante quanto la dimensione economica complessiva.

La variabile "Host" evidenzia un effetto positivo localizzato, indicando che la partecipazione come Paese ospitante può incrementare temporaneamente la performance olimpica, pur avendo un peso complessivo limitato nel modello.

Nel complesso, l’analisi SHAP conferma la presenza di relazioni complesse e non lineari tra le variabili, evidenziando come il successo olimpico sia il risultato di un’interazione tra fattori economici, demografici e strutturali.
``

## Confronto tra modelli

Per valutare l’efficacia dei modelli utilizzati, viene effettuato un confronto tra la regressione lineare e il modello Random Forest.

Questo confronto consente di verificare se l’aumento di complessità del modello non lineare sia giustificato da un miglioramento significativo della capacità predittiva.
"""

# Cella 28 : Confronto modelli
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

# Creiamo una "pipeline" che in automatico scala i dati (media 0, varianza 1)
# e dopo DOPO applica la regressione lineare.
lr = make_pipeline(StandardScaler(), LinearRegression())

# Addestriamo la pipeline

lr.fit(X_train, y_train)

# Predizioni in scala log e successiva conversione in reale
y_pred_lr_log = lr.predict(X_test)
y_pred_lr_real = np.expm1(y_pred_lr_log)

# Confronto R2 (tutto rigorosamente in scala reale)
print("--- Confronto Modelli (Scala Reale) ---")
print(f"Random Forest R2: {r2_score(y_test_real, y_pred_real):.3f}")
print(f"Linear Regression R2: {r2_score(y_test_real, y_pred_lr_real):.3f}")

"""### Analisi dei risultati

Il confronto tra i modelli evidenzia una differenza significativa in termini di capacità predittiva.

Il modello Random Forest presenta un coefficiente di determinazione pari a R² ≈ 0.44, risultando nettamente superiore rispetto alla regressione lineare, che si ferma a R² ≈ 0.21.

Questo risultato indica che il modello non lineare è in grado di catturare meglio la complessità del fenomeno, sfruttando relazioni non lineari e interazioni tra le variabili.

La regressione lineare, al contrario, mostra una capacità esplicativa limitata, evidenziando come il successo olimpico non possa essere adeguatamente descritto da relazioni puramente lineari.

Nel complesso, il confronto conferma che l’utilizzo di modelli più avanzati consente di migliorare significativamente la qualità delle previsioni, evidenziando la natura complessa e multidimensionale del fenomeno analizzato.

## Analisi approfondita dei residui

Per valutare in modo completo la qualità del modello, viene effettuata un’analisi dettagliata dei residui, considerando sia la distribuzione degli errori sia la loro variazione rispetto alle previsioni.

Questa analisi consente di individuare pattern sistematici, outlier e differenze nella capacità predittiva tra i diversi gruppi di Paesi.

##Analisi Residui
"""

# Cella 29 : Analisi dei residui


# =========================
# 1. Calcolo residui
# =========================

# Use the real-scale values for residuals
res = y_test_real - y_pred_real

df_residui = pd.DataFrame({
    'Valore_Reale': y_test_real,
    'Valore_Predetto': y_pred_real,
    'Residuo': res
}).sort_values('Residuo', ascending=False)

df_residui['Nazione'] = df_model.loc[y_test_real.index, 'Nazione']

print("Top 5 residui più alti (Paesi che hanno ottenuto molti più successi del previsto):")
display(df_residui.head())

print("\nTop 5 residui più bassi (Paesi che hanno performato sotto le attese):")
display(df_residui.tail())


# =========================
# 2. Scatter plot residui
# =========================

plt.figure(figsize=(10, 6))

sns.scatterplot(
    x=y_pred_real,
    y=res,
    alpha=0.7,
    color='#1f77b4',
    edgecolor='w',
    s=60
)

# Linea zero (perfetta previsione)
plt.axhline(y=0, color='red', linestyle='--', linewidth=2)

plt.title('Grafico dei Residui: Performance Random Forest', fontsize=14, fontweight='bold')
plt.xlabel('Valori Predetti (Score Medaglie)', fontsize=12)
plt.ylabel('Residui (Reale - Predetto)', fontsize=12)

plt.grid(True, linestyle=':', alpha=0.6)

plt.show()


# =========================
# 3. Distribuzione residui
# =========================

plt.figure(figsize=(10, 5))

sns.histplot(res, bins=30, kde=True, color='#1f77b4')

plt.title("Distribuzione dei Residui", fontsize=14, fontweight='bold')
plt.xlabel("Residui")
plt.ylabel("Frequenza")

plt.grid(True, linestyle=':', alpha=0.6)

plt.show()


# =========================
# 4. Statistiche residui
# =========================

print("\nStatistiche dei residui:")
print(df_residui['Residuo'].describe())

# Analisi residui per cluster

df_residui['Cluster'] = df_model.loc[y_test_real.index, 'Cluster_SocioEconomico']

print("\nMedia residui per cluster:")
print(df_residui.groupby('Cluster')['Residuo'].mean())

"""### Analisi dei risultati

L’analisi dei residui evidenzia una distribuzione fortemente concentrata intorno allo zero, indicando che il modello è in grado di descrivere correttamente la maggior parte delle osservazioni.

Tuttavia, la presenza di una lunga coda destra e di residui estremamente elevati segnala l’esistenza di alcuni casi in cui il modello sottostima significativamente la performance olimpica. In particolare, emergono Paesi come Cina, Russia e Regno Unito, caratterizzati da risultati sportivi molto superiori alle previsioni.

Il grafico dei residui rispetto ai valori predetti non mostra pattern sistematici evidenti, suggerendo l’assenza di errori strutturali nel modello. Tuttavia, la maggiore dispersione per valori elevati indica una difficoltà nel catturare correttamente le performance delle principali potenze olimpiche.

Le statistiche descrittive confermano questa evidenza: la distribuzione è asimmetrica e caratterizzata da una deviazione standard elevata, riflesso della forte variabilità nei risultati sportivi.

L’analisi per cluster evidenzia inoltre differenze significative: i Paesi appartenenti al cluster più sviluppato presentano residui medi più elevati, indicando una sistematica sottostima delle performance per le economie avanzate, mentre i cluster meno sviluppati mostrano errori più contenuti.

Nel complesso, questi risultati suggeriscono che il modello è efficace nel descrivere le tendenze generali, ma presenta limiti nel rappresentare i casi estremi, in cui intervengono fattori aggiuntivi non completamente catturati dalle variabili economiche.

Questo conferma che il successo olimpico, pur essendo fortemente legato alla dimensione economica, è influenzato anche da fattori strategici, istituzionali e culturali difficilmente quantificabili.

## Conclusioni

L’obiettivo del presente progetto era analizzare i determinanti del successo olimpico, con particolare attenzione al ruolo delle variabili economiche e socio-demografiche.

I risultati ottenuti evidenziano in modo chiaro come la dimensione economica complessiva, rappresentata dal PIL, costituisca il principale driver della performance olimpica. Questo risultato emerge in maniera consistente attraverso tutte le metodologie utilizzate, dalle analisi descrittive alle regressioni, fino ai modelli di machine learning.

L’analisi delle correlazioni e dei modelli lineari mostra una relazione positiva e significativa tra PIL e numero di medaglie, mentre il confronto con il PIL pro capite evidenzia come il benessere medio abbia un impatto più limitato rispetto alla capacità aggregata di investimento.

I modelli non lineari, in particolare il Random Forest, confermano e rafforzano questi risultati, mostrando una capacità predittiva superiore rispetto alla regressione lineare. Questo suggerisce che il fenomeno olimpico è caratterizzato da relazioni complesse e interazioni tra variabili, difficilmente catturabili attraverso modelli lineari semplici.

L’analisi dei cluster evidenzia inoltre una chiara segmentazione del sistema olimpico globale, distinguendo tra:
- Paesi altamente sviluppati e dominanti,
- economie intermedie,
- Paesi emergenti con performance limitate.

Questa struttura stratificata è ulteriormente confermata dalla profilazione multidimensionale e dalle analisi interattive, che mostrano come il successo olimpico sia strettamente legato alla posizione economica relativa dei Paesi.

L’analisi dei residui e degli outlier evidenzia tuttavia l’esistenza di deviazioni significative rispetto alle previsioni del modello, con la presenza di Paesi in grado di sovraperformare o sottoperformare rispetto alle attese. Questo risultato sottolinea il ruolo di fattori qualitativi non direttamente osservabili, quali politiche sportive, organizzazione istituzionale, cultura sportiva e investimenti strategici.

Le tecniche di Explainable AI (SHAP) confermano infine la centralità del PIL e chiariscono la natura non lineare del suo impatto, evidenziando come le economie più grandi beneficino di effetti amplificati nella produzione di risultati sportivi.

Nel complesso, il progetto dimostra che il successo olimpico è un fenomeno multidimensionale, in cui la disponibilità di risorse economiche rappresenta una condizione necessaria ma non sufficiente. La capacità di trasformare tali risorse in risultati sportivi dipende infatti da una combinazione di fattori strutturali, strategici e organizzativi.

Tra i principali limiti dello studio si segnalano:
- la presenza di variabili non osservate,
- l’eterogeneità del dataset,
- la difficoltà nel modellizzare eventi estremi e performance eccezionali.

Future estensioni del lavoro potrebbero includere:
- l’integrazione di variabili qualitative legate alle politiche sportive,
- l’analisi di dinamiche temporali più dettagliate,
- l’utilizzo di modelli ancora più avanzati per catturare interazioni complesse.

In conclusione, i risultati confermano l’ipotesi centrale del progetto: il successo olimpico è fortemente influenzato dalla capacità economica dei Paesi, ma non può essere spiegato interamente senza considerare il ruolo cruciale di fattori qualitativi e istituzionali.
"""